default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: buleleng
  host: localhost
  port: 5433

development:
  <<: *default
  database: Dompetku

test:
  <<: *default
  database: Dompetku_tes